(part "TMUX1209PWR"
    (packageRef "SOP65P640X120-16N")
    (interface
        (port "1" (symbPinId 1) (portName "A0") (portType INPUT))
        (port "2" (symbPinId 2) (portName "EN") (portType INPUT))
        (port "3" (symbPinId 3) (portName "NC") (portType INOUT))
        (port "4" (symbPinId 4) (portName "S1A") (portType INOUT))
        (port "5" (symbPinId 5) (portName "S2A") (portType INOUT))
        (port "6" (symbPinId 6) (portName "S3A") (portType INOUT))
        (port "7" (symbPinId 7) (portName "S4A") (portType INOUT))
        (port "8" (symbPinId 8) (portName "DA") (portType INOUT))
        (port "9" (symbPinId 9) (portName "DB") (portType INOUT))
        (port "10" (symbPinId 10) (portName "S4B") (portType INOUT))
        (port "11" (symbPinId 11) (portName "S3B") (portType INOUT))
        (port "12" (symbPinId 12) (portName "S2B") (portType INOUT))
        (port "13" (symbPinId 13) (portName "S1B") (portType INOUT))
        (port "14" (symbPinId 14) (portName "VDD") (portType POWER))
        (port "15" (symbPinId 15) (portName "GND") (portType GROUND))
        (port "16" (symbPinId 16) (portName "A1") (portType INPUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TMUX1209PWR")
    (property "Mouser_Part_Number" "595-TMUX1209PWR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TMUX1209PWR?qs=l7cgNqFNU1gbdZeh0oWOOQ%3D%3D")
    (property "Arrow_Part_Number" "TMUX1209PWR")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/tmux1209pwr/texas-instruments?utm_currency=USD&region=europe")
    (property "Description" "2-ch, 4:1 general purpose analog multiplexer with 1.8-V logic control")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/TMUX1209")
    (property "symbolName1" "TMUX1209PWR")
)
